# Generated by Django 2.2 on 2019-10-05 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_heisen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DateTimeField()),
                ('starting_time', models.DateTimeField()),
                ('no_of_questions', models.IntegerField()),
                ('questions', models.ManyToManyField(to='app_heisen.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intital_rating', models.IntegerField()),
                ('rating_change', models.IntegerField()),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('final_rating', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app_heisen.Contest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
