# Generated by Django 2.2 on 2019-10-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_heisen', '0002_contest_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='length',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='starting_time',
            field=models.TimeField(),
        ),
    ]
